### ISSUE TITLE
spare drone parts issue 

### ISSUE THREAD

**Issue by SonOfGorkamorka** [WhitePhant0m/RoR2-Mods#1]
if you have spare drone parts and pick up a new item, the upgrade spare parts gives your turrets disappears

**Comment by WhitePhant0m** [comment]
I think I've figured out what causes this, I'll get this fixed soon:tm:

**Comment by WhitePhant0m** [comment]
Version 0.0.2 *should* fix this issue, at least I got it to work on my end.
